version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - freecodecamp
    volumes:
      - /Users/claire/fow/fow-be/trigger.sql:/docker-entrypoint-initdb.d/trigger.sql
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - freecodecamp
  # redis_container:
  #   # 사용할 이미지
  #   image: redis:latest
  #   # 컨테이너명
  #   container_name: redis_test
  #   # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
  #   ports:
  #     - 6379:6379
  #   # 스토리지 마운트(볼륨) 설정
  #   volumes:
  #     - ./redis/data:/data
  #     - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
  #   # 컨테이너에 docker label을 이용해서 메타데이터 추가
  #   labels:
  #     - "name=redis"
  #     - "mode=standalone"
  #   # 컨테이너 종료시 재시작 여부 설정
  #   restart: always
  #   command: redis-server /usr/local/conf/redis.conf
networks:
  freecodecamp:
